### PR TITLE
Snewpy refactor

### PR DESCRIPTION
**Pull request by KaraMelih**
This factor replaces the default single line model call with a two step call where the user first needs to load the model from `snewpy` explicitly and pass that to `snax.Supernova_Models.Model` class. 

This offers more flexibility and avoids mistakes that happen on the background with the model selection.

Changes are shown in a tutorial notebook under notebooks

### CODE REVIEW

**Review by ricmperes — COMMENTED** [review]
Great work. It seems to decomplicate things overall. I'm going through the code changes briefly. Do you want me to give it a try and load/run a couple of sims. Or at least to select Bollig a number of times to check?

**Comment by KaraMelih** [comment]
Thanks! _Why not enjoy this PR with  [an iced filter coffee](https://www.youtube.com/watch?v=PApBycDrPo0&ab_channel=JamesHoffmann)_

Here are two notebooks where I used the package to load and investigate the models, then simulate using WFSim;

- https://github.com/XENONnT/analysiscode/blob/master/Multimessenger/Melih/investigate_models.ipynb
- https://github.com/XENONnT/analysiscode/blob/master/Multimessenger/Melih/Model_simulations.ipynb

and also [this notebook](https://github.com/XENONnT/multimessenger/blob/snewpy-refactor/notebooks/SNAX-tutorial.ipynb) within the package itself to show how to use it. 

I tried things fast so there may be some problems. If you try and notice anything that'd be great!

**Comment by KaraMelih** [comment]
One feature I wanted but couldn't successfully implement (apparently) is to track the metadata of the simulations in one single file; `/project2/lgrandi/xenonnt/simulations/supernova/simulation_metadata.csv`  <br>

Each time you simulate a supernova it was supposed to append more information about the simulated run in here, but I think it didn't work properly. Do not prioritize this, but if you think it is useful, and you have time, you could maybe take a look at that as well

**Comment by KaraMelih** [comment]
This code is used to check the simulated strax data folder and returns you all the successfully simulated data in there;

```python
from snax.sn_utils import see_simulated_contexts
df = see_simulated_contexts()
df.reset_index(inplace=True)
df.drop(columns="level_0", inplace=True)
print(np.unique(df.tag, return_counts=True))
df = df[df['tag']=='2023.05.2']
simulated_models = dict(tuple(df.groupby(by='sn_model')))
```

It looks into the `strax_data` then fetches the software versions that match the given hash, and it looks like for the hash we have 3 container has the same hash (curious stuff), that's why by default `df` is 3 times the actual data. I select only the `'2023.05.2'' tag. 

Then you can see the simulated data for all different models;
```pytohn
for k,v in simulated_models.items():
    print(f"{k:20} -> {len(v)}")
```
```
B16_m11              -> 21
B16_m27              -> 21
F21_m13              -> 21
N13_BHLS220          -> 21
N13_BHshen           -> 21
N13_m13              -> 21
N13_m50              -> 21
```

**Comment by KaraMelih** [comment]
> One feature I wanted but couldn't successfully implement (apparently) is to track the metadata of the simulations in one single file; `/project2/lgrandi/xenonnt/simulations/supernova/simulation_metadata.csv`
> 
> Each time you simulate a supernova it was supposed to append more information about the simulated run in here, but I think it didn't work properly. Do not prioritize this, but if you think it is useful, and you have time, you could maybe take a look at that as well

Well, actually it looks like it is actually working.
```
mf = fetch_metadataframe(B16_m11.conf_path)
df = see_simulated_contexts()
df.reset_index(inplace=True)
df.drop(columns="level_0", inplace=True)
df = df[df['tag']=='2023.05.2']
```
it just has 3 extra data entries. As every simulation writes to it but nothing removes from it when you delete some simulated data.

**Comment by ricmperes** [comment]
> Thanks! Why not enjoy this PR with [an iced filter coffee](https://www.youtube.com/watch?v=PApBycDrPo0&ab_channel=JamesHoffmann)

A beverage, an update and a tech tip. Where's the poem of this Digest? 😄 

> Well, actually it looks like it is actually working.

Right, the `simulation_metadata.csv` file is there and filled. To work as a log It seems to make sense to keep every entry instead of deleting, though. Or were you thinking more of a database where to see what was already simulated and ready to load?

**Comment by KaraMelih** [comment]
> where to see what was already simulated and ready to load?

Actually this is what `df = see_simulated_contexts()` does, the problem is if you look at the `df` there is `sim_id` and `sn_model` and you can see the distance in the simulations name, but say if you used the same model, but a different metallicity, the sim id and sn model will be identical and there is no other way to distinguish the two simulations.  Same with volume or different E fields. 

I thought it would be useful to this metaframe as a lookup table

**Pull request merged**
