### PR TITLE
Models

### PR DESCRIPTION
**Pull request by KaraMelih**
New things with Models branch;

- It is now a python package. 
- snewpy models can be used
- from any model until WFSim simulated straxen data all steps can be done with one package.
- many improvements and features. Please refer to tutorial notebooks under multimessenger/notebooks

### CODE REVIEW

**Comment by KaraMelih** [comment]
@ricmperes should we just merge this and make it the master branch? 
Later we can branch out from this.

**Comment by ricmperes** [comment]
It's tested and working so I think yes. The master is already too outdated and we keep working on `models` instead.

**Review by ricmperes — APPROVED** [review]
Code tested and working. Further review to be done during development.

**Comment by KaraMelih** [comment]
by the power vested in me by the collaboration of XENON and github, I now pronounce this branch merged

**Pull request merged**
