### PR TITLE
Automate simulation of models in cluster

### PR DESCRIPTION
**Pull request by ricmperes**
For mass sim production one should make use of the cluster infrastructure available. This PR aims to allow easy handling of submission of job for this task from and for any part of the simulation process (ligth curve, recoil spectrum, sampled quantities, wfsim results).

### CODE REVIEW

**Comment by KaraMelih** [comment]
I made 3 commits to this branch. and I commented on them. Please have a look, and see if you like them.

do we need to have a separate `scripts/` folder? It seems confusing. In a package, if I see multimessenger, and scripts folder, I'd think that the package scripts are under ./scripts folder. Maybe we change the name? or carry it under supernova subfolder?

**Comment by ricmperes** [comment]
The issue of putting the scripts directory one layer down (inside supernova) is that they'd become part of the package, which I would avoid. I'd like to keep them separate, as useful already-tested scripts that use the python package in question. That said, I don't mind changing the name. Any suggestion?

**Comment by KaraMelih** [comment]
I'm merging it as it is.
My initial idea was that this also becomes a part of the package. Similar to `A.simulate_one()` , one would have executed `A.submit_simulations(**args,**kwargs)`
but we can always revisit this idea in the future.

**Comment by ricmperes** [comment]
I see your idea. I can implement it that way later then and just execute that function on the script. I think it's still useful to have a directory for a collection of scripts. For instance standard plots generation or similar tasks.

**Pull request merged**
